homepage_filter:
  type: objects
  default: []
  schema:
    name: "filter"
    properties:
      tag:
        type: tags
        required: true
        validations:
          min_length: 1
      icon:
        type: string
      button_text:
        type: string

locale_filter:
  type: objects
  default: []
  schema:
    name: "locale"
    identifier: text
    properties:
      tag:
        type: tags
        required: true
        validations:
          min_length: 1
      text:
        type: string

svg_icons:
  default: "user-astronaut"

ios_url:
  default: "https://apps.apple.com/us/app/discourse-hub/id1173672076"

android_url:
  default: "https://play.google.com/store/apps/details?id=com.discourse&hl=en_US"
