homepage_filter:
  type: objects
  default: []
  schema:
    name: "filter"
    properties:
      tag:
        type: tags
        required: true
        validations:
          min_length: 1
      icon:
        type: string
      button_text:
        type: string

locale_filter:
  type: objects
  default: []
  schema:
    name: "locale"
    identifier: text
    properties:
      tag:
        type: tags
        required: true
        validations:
          min_length: 1
      text:
        type: string

promo_tile:
  type: objects
  default: []
  schema:
    name: "promo"
    properties:
      enabled:
        type: boolean
      position:
        type: integer
        validations:
          minimum: 1
      title:
        type: string
      description:
        type: string
      link:
        type: string
      image_url:
        type: string
      dark_image_url:
        type: string

svg_icons:
  default: "user-astronaut"
