homepage_filter:
  type: objects
  default: []
  schema:
    name: "filter"
    properties:
      tag:
        type: tags
        required: true
        validations:
          min_length: 1
      icon:
        type: string
      button_text:
        type: string

svg_icons:
  default: "user-astronaut"
